### ISSUE TITLE
Checkpoint not found for models

### ISSUE THREAD

**Issue by yuvalkry** [yash9439/Detectron-Layout-Parser#1]
Hello,

  Thank you for creating this example use of the layout parser!

   # Update: it is a problem in the layout parser:
             https://github.com/Layout-Parser/layout-parser/issues/168
  
   How to load the models? there is a problem with caching, is it a bug in the model
   or a problem with torch? how to resolve?

   The file is actually there but with '?dl=1' addition

ls -lt ~/.torch/iopath_cache/s/57zjbwv6gh3srry/
total 836212
-rw-r--r-- 1 yuval yuval 856276388 May 24 08:40 'model_final.pth?dl=1'
-rw-r--r-- 1 yuval yuval         0 May 24 08:40 'model_final.pth?dl=1.lock'

    Thanks,
           Yuval

config.yaml?dl=1: 8.19kB [00:01, 4.70kB/s]
model_final.pth?dl=1: 856MB [00:41, 20.8MB/s]
Traceback (most recent call last):
  File "/mnt/c/Users/yuval/Documents/recommender/src/detectron Layout Parser.py", line 25, in <module>
    model1 = lp.Detectron2LayoutModel('lp://PubLayNet/mask_rcnn_X_101_32x8d_FPN_3x/config',
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yuval/miniconda3/envs/recommender/lib/python3.11/site-packages/layoutparser/models/detectron2/layoutmodel.py", line 119, in __init__
    self._create_model()
  File "/home/yuval/miniconda3/envs/recommender/lib/python3.11/site-packages/layoutparser/models/detectron2/layoutmodel.py", line 122, in _create_model
    self.model = detectron2.engine.DefaultPredictor(self.cfg)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yuval/miniconda3/envs/recommender/lib/python3.11/site-packages/detectron2/engine/defaults.py", line 288, in __init__
    checkpointer.load(cfg.MODEL.WEIGHTS)
  File "/home/yuval/miniconda3/envs/recommender/lib/python3.11/site-packages/detectron2/checkpoint/detection_checkpoint.py", line 62, in load
    ret = super().load(path, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yuval/miniconda3/envs/recommender/lib/python3.11/site-packages/fvcore/common/checkpoint.py", line 153, in load
    assert os.path.isfile(path), "Checkpoint {} not found!".format(path)
AssertionError: Checkpoint /home/yuval/.torch/iopath_cache/s/57zjbwv6gh3srry/model_final.pth not found!

**Comment by yuvalkry** [comment]
Update: it is a problem in the layout parser:
         https://github.com/Layout-Parser/layout-parser/issues/168
